version: '{build}'
image: macos
environment:
  global:
    HAXELIB_ROOT: /Users/appveyor/haxelib
    HAXE_INSTALLDIR: /Users/appveyor/haxe_bin

install:
  - cd /Users/appveyor
  - brew install neko
  - brew install gnu-tar
  - brew install wget
  - brew install butler
  - wget "https://github.com/HaxeFoundation/haxe/releases/download/4.2.2/haxe-4.2.2-osx.tar.gz"
  - mkdir $HAXE_INSTALLDIR
  - tar -xf haxe-4.2.2-osx.tar.gz -C $HAXE_INSTALLDIR
  - export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20201231082044_5e33a78aa
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel -y
  - haxelib run lime setup -y
  - haxelib install flixel-tools
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib install linc_luajit
  - haxelib install actuate
  - haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
  # JOELwindows7: Android permissioner
  - haxelib install android6permissions
  - haxelib install androidhx
  - haxelib list
  - pwd
  - cd /Users/appveyor/projects/kaded-fnf-mods-macos

build_script:
  - haxelib run lime rebuild discord_rpc mac
  - haxelib run lime rebuild extension-webm mac
  - haxelib run lime rebuild linc_luajit mac # JOELwindows7: because it seems it only had windows?
  - haxelib run lime build mac
after_build:
  - hdiutil create /Users/appveyor/temp.dmg -ov -volname "last-funkin-moments-macOS" -fs HFS+ -srcfolder "/Users/appveyor/projects/kaded-fnf-mods-macos/export/release/mac/bin"
  - hdiutil convert /Users/appveyor/temp.dmg -format UDZO -o /Users/appveyor/last-funkin-moments-macOS.dmg
  # - gtar -cvf last-funkin-moments-macOS.tar -C /Users/appveyor/projects/kade-engine-macos/export/release/macos/bin .
  # JOELwindows7: upload to itch
  - if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then ./butler push /Users/appveyor/last-funkin-moments-macOS.dmg joelwindows7/last-funkin-moments:macOS-appveyor; fi

artifacts:
- path: "/Users/appveyor/last-funkin-moments-macOS.dmg"
  name: Last Funkin Moments for macOS
