# Taken from https://github.com/andyli/HaxeCI/blob/master/appveyor.yml
version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  # http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
  - ps: Set-Service wuauserv -StartupType Manual
  # Install the neko chocolatey package (https://chocolatey.org/packages/neko)
  - cinst neko -y
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe -y
  # JOELwindows7: Install the wget and stuffs
  # - cinst wget -y # downloader
  - cinst butler -y # upload to itch io
  # - cinst zip -y # zip it
  # - cinst unzip -y # unzip it
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # Install project dependencies
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel -y
  - haxelib run lime setup -y
  - haxelib install flixel-tools
  # haxelib run flixel-tools setup -y # Can't do this since it asks [y/n] even with -y argument! Stupid
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib install flixel-addons
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib install linc_luajit
  - haxelib install actuate
  - haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
  # JOELwindows7: Android permissioner
  - haxelib install android6permissions
  # - haxelib install androidhx
  - haxelib list

# No tests idk lol
build_script:
  - dir
  - haxelib run lime rebuild extension-webm windows
  - haxelib run lime build html5
  # haxelib run lime build linux # doesnt work if host OS is not same as that desktop OS

after_build:
  - dir
  # JOELwindows7: upload to itch
  # - if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then butler push C:\projects\export\release\html5\bin joelwindows7/last-funkin-moments:html5-appveyor; fi
  # wtf, appveyor did not expect Git
  - butler push C:\projects\export\release\html5\bin joelwindows7/last-funkin-moments:html5-appveyor

artifacts:
  - path: export/release/html5/bin
    name: last-funkin-moments-html5
    type: zip
