# Taken from https://github.com/andyli/HaxeCI/blob/master/appveyor.yml
version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib
    ANDROID_SDK_LOC: C:\projects\android_sdk
    ANDROID_NDK_ROOT_LOC: C:\projects\android_ndk
    ANDROID_CMD_LOC: C:\projects\android_cmd

install:
  # http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
  - ps: Set-Service wuauserv -StartupType Manual
  # Install the neko chocolatey package (https://chocolatey.org/packages/neko)
  - cinst neko -y
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe -y
  # JOELwindows7: Install the wget and stuffs
  - cinst wget -y # downloader
  - cinst butler -y # upload to itch io
  # - cinst zip -y # zip it
  # - cinst unzip -y # unzip it
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # android things
  - wget -q O openJDK.msi https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_windows_hotspot_8u292b10.msi
  - wget -q O android_ndk.zip https://dl.google.com/android/repository/android-ndk-r15c-windows-x86_64.zip?hl=fi
  - wget -q O android_cmd.zip https://dl.google.com/android/repository/commandlinetools-win-7302050_latest.zip
  - wget -q O android_sdk.zip https://dl.google.com/android/repository/platform-tools-latest-windows.zip
  - msiexec /i openJDK.msi INSTALLLEVEL=1 INSTALLDIR="c:\Program Files\AdoptOpenJDK\" /quiet
  - unzip .\android_ndk.zip "%ANDROID_NDK_ROOT_LOC%"
  - unzip .\android_cmd.zip "C:\projects\android_sdk\"
  - unzip .\android_sdk.zip "%ANDROID_SDK_LOC%"
  # Install project dependencies
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel -y
  - haxelib run lime setup -y
  - haxelib install flixel-tools
  # haxelib run flixel-tools setup -y # Can't do this since it asks [y/n] even with -y argument! Stupid
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib install flixel-addons
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git extension-webm https://github.com/KadeDev/extension-webm
  - C:\projects\android_sdk\cmdline-tools\bin\sdkmanager.bat "platform-tools" "platforms;android-19" "build-tools"
  - haxelib run lime config ANDROID_SDK "%ANDROID_SDK_LOC%"
  - haxelib run lime config ANDROID_NDK_ROOT "%ANDROID_NDK_ROOT_LOC%"
  - haxelib run lime config ANDROID_SETUP true
  - haxelib run lime config JAVA_HOME C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot
  - haxelib run lime rebuild extension-webm android
  - haxelib install linc_luajit
  - haxelib install actuate
  # - haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
  # JOELwindows7: Android permissioner
  - haxelib install android6permissions
  # - haxelib install androidhx
  - haxelib list

# No tests idk lol
build_script:
  - dir
  # - haxelib run lime rebuild extension-webm windows
  - haxelib run lime build android

after_build:
  - dir
  # JOELwindows7: upload to itch
  # wtf, appveyor did not expect Git
  - butler push "C:\projects\kaded-fnf-mods-winDroid\export\release\android\bin\app\build\output\apk\Last Funkin Moments-debug.apk" joelwindows7/last-funkin-moments:android-appveyor

artifacts:
  - path: export\release\android\bin\app\build\output\apk\Last Funkin Moments-debug.apk
    name: last-funkin-moments-android
    # type: zip
  # - path: export/32bit/windows/bin
  #   name: last-funkin-moments-windows32
  #   type: zip
  # - path: export/release/html5/bin
  #   name: last-funkin-moments-html5
  #   type: zip
