version: '{build}'
image: Ubuntu
environment:
  global:
    HAXELIB_ROOT: /home/appveyor/haxelib
    HAXE_INSTALLDIR: /home/appveyor/haxe
    BUTLER_DIR: /home/appveyor/

install:
  - cd /home/appveyor
  - sudo add-apt-repository ppa:haxe/releases -y
  - sudo apt update
  - sudo apt install build-essential -y
  - sudo apt-get install gcc-multilib g++-multilib -y
  - sudo apt install neko tar -y
  - wget https://github.com/HaxeFoundation/haxe/releases/download/4.2.2/haxe-4.2.2-linux64.tar.gz
  - mkdir -p $HAXE_INSTALLDIR
  - tar -xf haxe-4.2.2-linux64.tar.gz -C $HAXE_INSTALLDIR
  - export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20210514141333_a2f4ba9
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel -y
  - haxelib run lime setup -y
  - haxelib install flixel-tools
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib git faxe https://github.com/uhrobots/faxe
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - haxelib git extension-webm https://github.com/KadeDev/extension-webm
  - haxelib run lime rebuild extension-webm linux
  - haxelib install linc_luajit
  - haxelib install actuate
  # - haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
  # JOELwindows7: Android permissioner
  - haxelib install android6permissions
  # - haxelib install androidhx
  - haxelib list
  # JOELwindows7: okay now the butler
  - wget -q -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
  - unzip butler.zip
  - chmod +x ./butler
  # see where we are, what contents are now, and then go into the project.
  - pwd
  - ls
  - cd /home/appveyor/projects/kaded-fnf-mods-linux

build_script:
  - cd /home/appveyor/projects/kaded-fnf-mods-linux
  # - haxelib run lime rebuild discord_rpc linux
  # - haxelib run lime rebuild extension-webm linux
  # - haxelib run lime rebuild linc_luajit linux # JOELwindows7: because it seems it only had windows?
  - haxelib run lime build linux
  - haxelib run lime build linux -32 -D32bit

after_build:
  - cd ~
  - pwd
  - ls
  - tar -cvf last-funkin-moments.tar -C /home/appveyor/projects/kaded-fnf-mods-linux/export/release/linux/bin .
  # - tar -cvf last-funkin-moments-32bit.tar -C /home/appveyor/projects/kaded-fnf-mods-linux/export/32bit/linux/bin .
  # JOELwindows7: upload to itch
  # - if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then /home/appveyor/butler push /home/appveyor/projects/kaded-fnf-mods-linux/export/release/linux/bin joelwindows7/last-funkin-moments:linux-appveyor; fi
  # - if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then /home/appveyor/butler push /home/appveyor/projects/kaded-fnf-mods-linux/export/32bit/linux/bin joelwindows7/last-funkin-moments:linux32-appveyor; fi
  # wtf appveyor did not expect git
  - /home/appveyor/butler push /home/appveyor/projects/kaded-fnf-mods-linux/export/release/linux/bin joelwindows7/last-funkin-moments:linux-appveyor
  # - /home/appveyor/butler push /home/appveyor/projects/kaded-fnf-mods-linux/export/32bit/linux/bin joelwindows7/last-funkin-moments:linux32-appveyor

artifacts:
- path: /home/appveyor/last-funkin-moments.tar
  name: Last Funkin Moments for Linux
# - path: last-funkin-moments-32bit.tar
#   name: Last Funkin Moments for Linux 32Bit
