# https://github.com/Perkedel/Where_Is_LoadingBar_Functionality/blob/master/.circleci/config.yml
# # https://nakyle.com/godot-ci/
version: 2.1
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
        name: Just check updates & install dependencies
        command: |
          sudo apt-get update
          sudo apt-get -y install wget zip unzip
      - run:
        name: setup Haxe and libraries
        environment:
          HAXELIB_ROOT: /home/appveyor/haxelib
          HAXE_INSTALLDIR: /home/appveyor/haxe
        command: |
        cd /home/appveyor
        sudo add-apt-repository ppa:haxe/releases -y
        sudo apt update
        sudo apt install neko tar -y
        wget https://github.com/HaxeFoundation/haxe/releases/download/4.1.5/haxe-4.1.5-linux64.tar.gz
        mkdir $HAXE_INSTALLDIR
        tar -xf haxe-4.1.5-linux64.tar.gz -C $HAXE_INSTALLDIR
        export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20201231082044_5e33a78aa
        mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
        haxelib install lime 7.9.0
        haxelib install openfl
        haxelib install flixel
        haxelib run lime setup flixel
        haxelib run lime setup
        haxelib install flixel-tools
        haxelib install flixel-addons
        haxelib install flixel-ui
        haxelib install hscript
        haxelib install newgrounds
        haxelib git faxe https://github.com/uhrobots/faxe
        haxelib git polymod https://github.com/larsiusprime/polymod.git
        haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
        haxelib install linc_luajit
        haxelib list
      - run:
        name: Just build this game already Linux
        command: |
        cd /home/appveyor/projects/kaded-fnf-mods
        haxelib run lime build linux
        tar -cvf funkin-linux.tar -C /home/appveyor/projects/kade-engine-linux/export/release/linux/bin
      - run:
        name: Just build this game already Windows
        command: |
        cd /home/appveyor/projects/kaded-fnf-mods
        haxelib run lime build windows
        zip -r funkin-windows.zip /home/appveyor/projects/kade-engine-linux/export/release/windows/bin
      - run:
        name: Just build this game already macOS
        command: |
        cd /home/appveyor/projects/kaded-fnf-mods
        haxelib run lime build mac
        tar -cvf funkin-mac.tar -C /home/appveyor/projects/kade-engine-linux/export/release/macos/bin
      - run:
        name: Just build this game already HTML5
        command: |
        cd /home/appveyor/projects/kaded-fnf-mods
        haxelib run lime build html5
        tar -cvf funkin-html5.tar -C /home/appveyor/projects/kade-engine-linux/export/release/html5/bin

