# https://github.com/Perkedel/Where_Is_LoadingBar_Functionality/blob/master/.circleci/config.yml
# # https://nakyle.com/godot-ci/
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run:
          name: Just check updates & install dependencies
          command: |
            sudo apt-get update
            sudo apt-get -y install wget zip unzip
      - run:
          name: setup Haxe and libraries and built them all
          environment:
            HAXELIB_ROOT: ~/haxelib
            HAXE_INSTALLDIR: ~/haxe
          command: |
            cd ~
            sudo add-apt-repository ppa:haxe/releases -y
            sudo apt update
            sudo apt install build-essential -y
            sudo apt-get install gcc-multilib g++-multilib -y
            sudo apt install neko tar -y
            wget https://github.com/HaxeFoundation/haxe/releases/download/4.2.2/haxe-4.2.2-linux64.tar.gz
            mkdir -p $HAXE_INSTALLDIR
            tar -xf haxe-4.2.2-linux64.tar.gz -C $HAXE_INSTALLDIR
            export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20210514141333_a2f4ba9
            mkdir -p $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
            haxelib install lime
            haxelib install openfl
            haxelib install flixel
            haxelib run lime setup flixel -y
            haxelib run lime setup -y
            haxelib install flixel-tools
            haxelib install flixel-addons
            haxelib install flixel-ui
            haxelib install hscript
            haxelib install newgrounds
            haxelib git faxe https://github.com/uhrobots/faxe
            haxelib git polymod https://github.com/larsiusprime/polymod.git
            haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
            haxelib install linc_luajit
            haxelib install actuate
            haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
            haxelib install android6permissions
            haxelib install androidhx
            haxelib list
            wget -q -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
            unzip butler.zip
            chmod +x ./butler
            pwd
            ls
            echo ha hi ha hu huha
            haxelib run lime rebuild extension-webm linux
            haxelib run lime rebuild linc_luajit linux
            cd ~/projects/kaded-fnf-mods

      # - run:
      #     name: Rebuild GrowtopiaFli video cutsceners
      #     command: |
      #       haxelib run lime rebuild extension-webm linux
      - run:
          name: Just build this game already Linux
          command: |
            cd ~/projects/kaded-fnf-mods
            haxelib run lime build linux
            haxelib run lime build linux -32 -D32bit
            tar -cvf last-funkin-moments.tar -C ~/projects/kaded-fnf-mods/export/release/linux/bin .
            tar -cvf last-funkin-moments-32bit.tar -C ~/projects/kaded-fnf-mods/export/32bit/linux/bin .
            if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then ./butler push ~/projects/kaded-fnf-mods/export/release/linux/bin joelwindows7/last-funkin-moments:linux-circleCI; fi
            if [[ $(git log -1 --oneline) == *"[RELEASE]"* ]]; then ./butler push ~/projects/kaded-fnf-mods/export/32bit/linux/bin joelwindows7/last-funkin-moments:linux32-circleCI; fi
      # - run:
      #     name: Just build this game already Windows
      #     command: |
      #       cd ~/projects/kaded-fnf-mods
      #       haxelib run lime build windows
      #       zip -r last-funkin-moments-windows.zip ~/projects/kaded-fnf-mods/export/release/windows/bin
      # - run:
      #     name: Just build this game already macOS
      #     command: |
      #       cd ~/projects/kaded-fnf-mods
      #       haxelib run lime build mac
      #       tar -cvf last-funkin-moments-mac.tar -C ~/projects/kaded-fnf-mods/export/release/macos/bin
      - run:
          name: Just build this game already HTML5
          command: |
            cd ~/projects/kaded-fnf-mods
            haxelib run lime build html5
            tar -cvf last-funkin-moments-html5.tar -C ~/projects/kaded-fnf-mods/export/release/html5/bin
      ########## unfortunately that each run did not recognize each other

